agent-name: chutney-server-agent-0
server:
  instance-name: Local instance
  port: 8350
  http:
    port: 9350
    interface: localhost
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
      tracking-modes: cookie

management:
  server:
    port: -1
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        exclude: "*"
    jmx:
      exposure:
        exclude: "*"

spring:
  application:
    name: chutney-server
  liquibase:
    change-log: classpath:/changelog/db.changelog-master.xml
  profiles:
    active:
      - db-h2

chutney:
  configuration-folder: .chutney/conf
  environment:
    configuration-folder: ${chutney.configuration-folder}/environment
  jira:
    configuration-folder: ${chutney.configuration-folder}/jira

  server:
    execution:
      async:
        publisher:
          ttl: 5
          debounce: 250

  engine:
    reporter:
      publisher:
        ttl: 5

  actions:
    sql:
      max-logged-rows: 20

  component:
    orient:
      path: .chutney/data/orient
      contextConfiguration:
        "[storage.diskCache.diskFreeSpaceLimit]": 384
        "[storage.diskCache.bufferSize]": 1024
